### ISSUE TITLE
交叉编译到路由器，无法获取硬盘序列号

### ISSUE THREAD

**Issue by ifwangs** [updateing/minieap#2]
无法从 /etc/mtab 获取根分区挂载设备信息，请使用 --fake-serial 选项手动指定硬盘序列号: Inappropriate ioctl for device (25)

**Comment by updateing** [comment]
这不是本项目的问题。


1. 路由器有“硬盘”这种东西吗……就目前的路由器来看，FTL都没有吧。单纯的MTD设备并不存在序列号这个属性。
2. 最后认证失败吗？失败的话，官方Linux客户端能否认证？能的话，麻烦提供下官方客户端认证的抓包，谢谢。

**Comment by ifwangs** [comment]
认证失败，而且学校只允许win客户端认证

**Comment by updateing** [comment]
认证失败的提示是“请使用管理员指定的客户端”吗？原版MentoHUST以及带v4的MentoHUST能否认证？

**Comment by ifwangs** [comment]
用户不允许使用本服务

**Comment by ifwangs** [comment]
win版mentohust可以

**Comment by updateing** [comment]
请把Windows官方客户端下显示的服务名用`--service`参数提供给程序。如果服务名是中文，则需要抓包后找到服务名的十六进制表示，用如下方式提供（因为编码不同所以要这么做）

```
SERVICE=`echo -ne "\xbd\xcc\xd3\xfd\xcd\xf8\xbd\xd3\xc8\xeb"`
minieap -n xxxx -u xxxxx -p xxxx --module rjv3 --service $SERVICE
```

至于服务名的寻找，可编译[这个程序](https://github.com/HamsterReserved/misc_scripts/blob/master/rj_property_reader.c)，将抓包的pcap文件路径作为参数，然后寻找`header->type = 0x39`的属性的值。

**Comment by ifwangs** [comment]
好的，晚上回去试试

**Comment by updateing** [comment]
现在问题解决了吗？
