### ISSUE TITLE
minieap与mentohust使用的一些问题

### ISSUE THREAD

**Issue by nature2608** [updateing/minieap#23]
你好，我在使用minieap的时候加V3参数提示锐捷版本低，此时已经加了-v参数
在mentohust使用的时候（ubuntu 16.04）拷suconfig.dat，w32n55.dll，802.1x进/etc/menohust，不带认证数据包mpf的时候提示客户端版本为5.0（win客户端是6.0的），提示客户端版本低。带数据包版本提示是6.0，但是提示"使用了非管理员指定的客户端"
所以在想是不是802.1x的问题，读出来的是不是版本有错误，加-v 也没用，希望又大神解答下。抓包对比看不出来有什么不同。
希望能得到回答！谢谢。

**Comment by updateing** [comment]
很抱歉，我已经不在学校了，所以现在已经没法确认到底是什么问题。不过在 minieap 里，`--version` 接受的是一个版本字符串而非 MentoHUST 那样的小数。minieap 也并不支持 MentoHUST 里使用小数的这部分逻辑，可以参考一下 MentoHUST 对这个参数的处理……

更主要的是，“使用非管理员指定的客户端”并不一定意味着就是版本号有误，很可能表示其他字段也有问题。可以用[这个工具](https://github.com/HamsterReserved/misc_scripts/blob/master/rj_property_reader.c)来看具体有什么字段、跟现在的有什么区别。直接用 pcap 文件作为参数传进去就好。

不过考虑到现在这么多 6.x 客户端报不能用的，我怀疑是包格式和所需字段有变化……

**Comment by nature2608** [comment]
谢谢你的回复，用那个工具看我也看不出什么东东😂。
分别抓包看16进制包头，尾都有不同的地方。可能需要修改包才能匹配了。

发自我的 iPhone

**Comment by nature2608** [comment]
@updateing 可否我抓包再修改源码里的包长度和数据？能否出可教程需要具体修改哪些包与哪些具体的数据，因为看了一篇修改V4的文章但是与V3有点不同（<ahref="https://codingstory.com.cn/mo-gai-mentohust-v4ban-ben-de-xin-de/">文章链接</a>），所以无从下手，希望指点。
`这段start包的ip，dns等信息在第二行，我抓包的是在最后面`
tatic uint8_t pkt_start_priv_header[] = {
                0xff, 0xff, 0x37, 0x77, 0x7f, 0xff, /*   ..7w.I */ /* Would be different in second auth */
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, /* Pv4NMSKG */ /* IPv4, NetMaSK, GaTeWaY, Primary DNS */
    0xff, 0xff, 0xff, 0xac, 0xb1, 0xff, 0xb0, 0xb0, /* TWYPDNS. */
    0x2d, 0x00, 0x00, 0x13, 0x11, 0x38, 0x30, 0x32, /* -....802 */
    0x31, 0x78, 0x2e, 0x65, 0x78, 0x65, 0x00, 0x00, /* 1x.exe.. */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* ........ */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* ........ */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, /* ........ */
//    0x02, 0x00, 0x00, 0x00, 0x13, 0x11, 0x01, 0xb1, /* ........ */
};

![_20171110013339](https://user-images.githubusercontent.com/32662472/32619972-4a366540-c5b7-11e7-8c37-0b164ea2f684.png)

**Comment by nature2608** [comment]
@updateing 
![qq 20171111154327](https://user-images.githubusercontent.com/32662472/32687433-1746bc16-c6f7-11e7-98fd-6ea6dc25a32f.png)
右边的是客户端的包，搞不懂什么意思，客户端版本修改后已经是跟客户端一样的数据了

**Comment by updateing** [comment]
这样看起来不好分析…… 可以直接拿上面那个字段分析工具显示的结果丢 Beyond Compare 看。

**Comment by nature2608** [comment]
我现在使用minieap-gzhu版本可以认证，但是不能心跳，心跳包已发出，抓包对比后变化的字段不同，是不是会导致不能心跳？
![inked minieap_li](https://user-images.githubusercontent.com/32662472/37700141-5071151a-2d25-11e8-9214-9e7186e7a6c7.jpg)

**Comment by updateing** [comment]
这两个字段是由服务器端给定的随机值生成出来的，每次认证后的起始值都不一样。看起来心跳包格式倒没什么问题。

**Comment by nature2608** [comment]
是的，格式是没什么问题。但是不能心跳。不知道是不是某个字段提取有错误导致计算错误。

**Comment by nature2608** [comment]
有没有什么办法解决？可以提供测试环境

**Comment by updateing** [comment]
建议分析一下官方的心跳，看看它发出的 echoNo 和最初的 key 有什么关系，以及 echoNo 的变化规律…… 这几个数值都是用“取反后高低位颠倒”这个方式编码的。
