### ISSUE TITLE
make clean 会产生文件（这算 bug）

### ISSUE THREAD

**Issue by hosiet** [updateing/minieap#27]
你好，

在代码顶层目录运行 `make clean` 会产生新的文件：

* if_impl/bpf/if_impl_bpf.d
* if_impl/libpcap/if_impl_libpcap.d

这显然不符合 `make clean` 应当做的事情，会导致某些情况下的问题（例如构建 deb 包出错）。

请考虑研究并处理这个问题。

**Comment by Z-Y00** [comment]
可以参考这个patch ～～～

https://salsa.debian.org/zouyoo-guest/minieap/blob/master/debian/patches/fix-makefile-clean.patch

**Comment by updateing** [comment]
这个问题有以下两个原因：

1. append.mk 中的 `-include` 仍然会导致重新生成 .d 文件
2. 未被选择的模块不会执行 clean，因为不在 `$(BUILD_MODULES)` 中了

我推送了一个新的[分支](https://github.com/updateing/minieap/commits/clean-fix)，有两个 commit 分别解决这两个问题（感谢 @Z-Y00 的 patch）

不过个人倾向添加一个 distclean 之类的目标专门用于清空所有模块产生的文件，各位想法如何？

**Comment by updateing** [comment]
已 merge 现有的方法，另一种想法并没有好看很多…… 感谢大家的建议。
