### ISSUE TITLE
macOS 支持

### ISSUE THREAD

**Issue by ysc3839** [updateing/minieap#29]
https://github.com/updateing/minieap/blob/227a665cfdfed64d5f60370ca3344a3891a6876d/util/net_util.c#L274-L279
可参考 netstat 的代码？
https://opensource.apple.com/source/network_cmds/network_cmds-543/netstat.tproj/route.c.auto.html

**Comment by ysc3839** [comment]
net_util.c.patch
https://gist.github.com/ysc3839/a5b336bcb791bb101ef863305dab4cf6

**Comment by updateing** [comment]
非常感谢！我这边 macOS 不作主用了，只是简单试了一下，取得数据没有问题。稍后合并。
