### ISSUE TITLE
请问minieap对多拨的支持如何？

### ISSUE THREAD

**Issue by LaboratoryK** [updateing/minieap#30]
支持用虚拟WAN多拨吗，
如何实现呢

**Comment by updateing** [comment]
minieap 目前没有实现单实例运行的限制，可以直接开任意多个，分别在不同的 WAN 口上认证。

此外，802.1x 认证一般不叫作“拨号”吧……

**Comment by updateing** [comment]
长时间无回应，关闭此 issue. 如有疑问可 reopen.
