### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by SidekickLx** [updateing/minieap#31]
Error occurs while compiling Minieap on O2 and O3 level

```
cc  -Iutil/ -Iinclude -O3  -Wall -Wpedantic -D_GNU_SOURCE  util/pid_lock.c -c -o util/pid_lock.o
In file included from /usr/include/fcntl.h:289:0,
                 from /usr/include/x86_64-linux-gnu/sys/file.h:24,
                 from util/pid_lock.c:1:
In function ‘open’,
    inlined from ‘pid_lock_init’ at util/pid_lock.c:29:19:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
    ^
/home/ericlee/minieap/append.mk:22: recipe for target 'util/pid_lock.o' failed
make: *** [util/pid_lock.o] Error 1
```
Here are some info
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)`
`Target: x86_64-linux-gnu`
```
#### Choose/Add your modules here ####
PLUGIN_MODULES := \       
 packet_plugin_printer \        
packet_plugin_rjv3
# Linux
PLUGIN_MODULES += if_impl_sockraw
# macOS / BSD
# PLUGIN_MODULES += if_impl_bpf

# Other OS
# PLUGIN_MODULES += if_impl_libpcap

# This implementation is not included in the code.
# If you need it, add it yourselves.
# PLUGIN_MODULES += ifaddrs

ENABLE_DEBUG  := false
ENABLE_ICONV  := false
ENABLE_GBCONV := false
STATIC_BUILD  := false
# If your platform has iconv_* integrated into libc, change to false
# Affects dynamic linking
LIBICONV_STANDALONE := false
CUSTOM_CFLAGS := -O3
CUSTOM_LDFLAGS :=
CUSTOM_LIBS :=

# Example for cross-compiling
# CC := arm-brcm-linux-uclibcgnueabi-gcc
# ENABLE_ICONV := true
```

And checkout [this](https://github.com/pantheon-systems/fusedav/issues/204) and [this](https://stackoverflow.com/questions/25706291/error-in-using-open-in-cuda-c), hope it would help :)

Good day

**Comment by Z-Y00** [comment]
why not launch a pull request, for there seems only a small tweak needed )

________________________________

**Comment by SidekickLx** [comment]
Actually I use this project for some binary researches. Thus I never played
with this project before, and I am not sure about the third argument of
that open() function.
When I tried to build, the issue just occurred. So I just raised the issue
and continued working 😓.
I think it should be
`pid_lock_fd = open(pidfile, O_RDWR | O_CREAT, 0644);`
let me send a request.
Thanks so much.



櫻川 Y00 <notifications@github.com> 于2018年8月8日周三 下午5:38写道：
