### ISSUE TITLE
不允许的客户端类型

### ISSUE THREAD

**Issue by Droid-MAX** [updateing/minieap#4]

**Comment by updateing** [comment]
官方Linux客户端可以用吗？

**Comment by Droid-MAX** [comment]
不能，win版的客户端版本是4.99，之前用的是agentx1，但校园网最近调整变动后用agentx1的话就是5分钟掉线。。。。

**Comment by updateing** [comment]
1. 这个客户端的算法是MentoHUST v4的，因此要求与原版一致，即官方提供Linux版且可用。只有Windows版的话可能是不行。
2. agentx1是代理认证吗？

**Comment by Droid-MAX** [comment]
https://bitbucket.org/CrazyBoyFeng/agentx1
用的狂风男的agentx1双向代理

**Comment by updateing** [comment]
我也想起来了。

目前还是抓包更方便一点……

**Comment by Droid-MAX** [comment]
你的minieap和mentohust-proxy项目，我针对mt7620平台的路由器编译出了现成的可执行程序，虽然在我们校园网环境下没有作用。。
http://pan.baidu.com/s/1hrEmVsg

**Comment by updateing** [comment]
谢谢！

这两个项目的心跳算法是一样的，只有一点点数据。MentoHUST v4原版也是这样 (虽然v2的wiki里说还需要带上锐捷的那一大堆东西，可是v2自己好像也没带啊……)

等抓到包再看心跳包是什么格式吧。

**Comment by Droid-MAX** [comment]
官方提供的xrgsu早已被废弃，只有Windows版客户端可用，我用mentohust跟minieap都提示不允许的客户端类型，这还有希望吗？

**Comment by updateing** [comment]
不敢下定论……毕竟还有几个认证字段含义未知（不过知道了估计也没啥用，算法好像有差别）

搞定心跳或许是个比较可行的办法……

**Comment by updateing** [comment]
（这个问题上目前似乎没有什么可以做的了）

**Comment by CrazyBoyFeng** [comment]
我离校的时候，网络中心已经升级锐捷4.99了。当时从网络中心锐捷计费后台看到上面的客户端状态是“不在线”，不过那时还没有5分钟掉线机制。所以我一直不知道这个5分钟检测是什么机制。我猜测是eap协议以外的东西，比如tcp\udp\http。
