### ISSUE TITLE
支持iNode的Portal认证吗？

### ISSUE THREAD

**Issue by Howard20181** [updateing/minieap#49]
客户端版本号为V7.10-0313
网上找到的都是802.1x的

**Comment by updateing** [comment]
不支持。这个程序只做 802.1x 认证。

Portal 认证不是比 802.1x 好解决多了么？至少啥都在浏览器里面，自带跨平台、跨架构能力。

**Comment by Howard20181** [comment]
> 不支持。这个程序只做 802.1x 认证。
> 
> Portal 认证不是比 802.1x 好解决多了么？至少啥都在浏览器里面，自带跨平台、跨架构能力。

我学校屏蔽了网页登录，只能使用客户端登录，网页登录我试过都是报客户端版本错误

**Comment by updateing** [comment]
是指用客户端登陆 Portal 页面？

**Comment by Howard20181** [comment]
> 是指用客户端登陆 Portal 页面？

不是，没有portal页面，直接INode客户端登录
![QQ截图20190930124019](https://user-images.githubusercontent.com/40033067/65850006-87c99e80-e37f-11e9-8d20-d8e23774fe41.png)

**Comment by updateing** [comment]
不了解 iNode 的设计，可以抓包看看到底是如何认证的。由于本项目目前没有支持，故先关闭了。

**Comment by Howard20181** [comment]
> 不了解 iNode 的设计，可以抓包看看到底是如何认证的。由于本项目目前没有支持，故先关闭了。

嗯嗯，我试过抓包
电脑客户端认证时发送了这么一个UDP包
<data><i n="userName">学号@huawei2.com</i><i n="hwAddr">MAC地址</i><i n="clientPort">10102</i><i n="clientVersion">CH V7.10-0313</i><i n="clientDisVersion">CH iNode PC 7.1 (E0313)</i><i n="isIndependent">1</i><i n="patchStamp">0</i><i n="SupSoftRunCheckType">true</i><i n="supBlackWhiteGroup">true</i><i n="supPureWhiteGroup">true</i><i n="supProcessCheckMD5">true</i><i n="supBWGroupWithDtl">true</i><i n="iSupCmp">true</i><i n="ClientType">PC</i><i n="ipv6Addr"></i><i n="ipAddr">10.10.36.20</i><i n="hostname">电脑主机名</i><i n="IsDomainUser">false</i><i n="BindToDomain"></i><i n="LogonDomain"></i><i n="DamClientId">动态连接ID（但同个账号在同个电脑登录似乎不变）</i><i n="iSupWanControl">false</i><i n="iSupOnlineUnauthNetAudit">false</i><i n="iSupACL">false</i><i n="iSupURL">false</i><i n="iSupRegHighOS">true</i><i n="iSupAlias">true</i><i n="OSInfo">系统版本</i><i n="CustomerizedTime">2017-02-13 17:40:06</i><i n="iSupOnlyWAV">true</i><i n="iSupShareCheck">1</i><i n="iSupAntiServiceMonitor">true</i><i n="diskDriveID">硬盘ID</i><i n="iSupblackssid">false</i><i n="vendor">电脑品牌</i><i n="model">电脑型号</i></data>

**Comment by Howard20181** [comment]
`<data><i n="userName">学号@huawei2.com</i><i n="hwAddr">MAC地址</i><i n="clientPort">10102</i><i n="clientVersion">CH V7.10-0313</i><i n="clientDisVersion">CH iNode PC 7.1 (E0313)</i><i n="isIndependent">1</i><i n="patchStamp">0</i><i n="SupSoftRunCheckType">true</i><i n="supBlackWhiteGroup">true</i><i n="supPureWhiteGroup">true</i><i n="supProcessCheckMD5">true</i><i n="supBWGroupWithDtl">true</i><i n="iSupCmp">true</i><i n="ClientType">PC</i><i n="ipv6Addr"></i><i n="ipAddr">10.10.36.20</i><i n="hostname">电脑主机名</i><i n="IsDomainUser">false</i><i n="BindToDomain"></i><i n="LogonDomain"></i><i n="DamClientId">动态连接ID（但同个账号在同个电脑登录似乎不变）</i><i n="iSupWanControl">false</i><i n="iSupOnlineUnauthNetAudit">false</i><i n="iSupACL">false</i><i n="iSupURL">false</i><i n="iSupRegHighOS">true</i><i n="iSupAlias">true</i><i n="OSInfo">系统版本</i><i n="CustomerizedTime">2017-02-13 17:40:06</i><i n="iSupOnlyWAV">true</i><i n="iSupShareCheck">1</i><i n="iSupAntiServiceMonitor">true</i><i n="diskDriveID">硬盘ID</i><i n="iSupblackssid">false</i><i n="vendor">电脑品牌</i><i n="model">电脑型号</i></data>`
