### ISSUE TITLE
mac os无法维持心跳包

### ISSUE THREAD

**Issue by bigtaotao** [updateing/minieap#50]
我编译了minieap并且使用了-b 1 操作,但是它还是无法维持心跳包,直接退出程序,5min之后断线 ps -e|grep mini 找不到进程

**Comment by updateing** [comment]
请抓包确认心跳包是否真的没有发出。我遇到过几例心跳包有定时发，但服务端不认的情况，需要区分开。

后面这种情况的话，可尝试把心跳包间隔降低到 20s 左右。如果还无效，可能就不太好修了。

**Comment by bigtaotao** [comment]
我发现是主进程退出的缘故 加了个死循话就正常了

发自我的iPhone
