### ISSUE TITLE
二次认证第二次没有带上IPv4信息

### ISSUE THREAD

**Issue by phpasppy** [updateing/minieap#53]
![minieap](https://cdn.icewx.com/2019/10/111.jpg)
minieap二次认证第二次没有带上IP、网关和掩码，学校自助管理页面不能显示正确IP

**Comment by liangjies** [comment]
已经解决了，问题出在这
https://github.com/updateing/minieap/blob/ddad50c0a60f096da09f3b2269f4c7b9ed4072d3/packet_plugin/rjv3/packet_plugin_rjv3_priv.c#L337
succ_count >= 2改成succ_count >= 1
