### ISSUE TITLE
添加锐捷模块后编译失败

### ISSUE THREAD

**Issue by JIANG3330** [updateing/minieap#54]
/usr/bin/ld: packet_plugin/rjv3/rjv3_hashes/checkV4.o:(.rodata+0x0): multiple definition of `array'; packet_plugin/rjv3/rjv3_hashes/checkV4.o:(.rodata+0x0): first defined here
/usr/bin/ld: packet_plugin/rjv3/rjv3_hashes/checkV4.o:(.rodata+0x720): multiple definition of `array_1'; packet_plugin/rjv3/rjv3_hashes/checkV4.o:(.rodata+0x720): first defined here
/usr/bin/ld: packet_plugin/rjv3/rjv3_hashes/checkV4.o: in function `display':
checkV4.c:(.text+0x0): multiple definition of `display'; packet_plugin/rjv3/rjv3_hashes/checkV4.o:checkV4.c:(.text+0x0): first defined here
/usr/bin/ld: packet_plugin/rjv3/rjv3_hashes/checkV4.o: in function `computeV4':
checkV4.c:(.text+0x76): multiple definition of `computeV4'; packet_plugin/rjv3/rjv3_hashes/checkV4.o:checkV4.c:(.text+0x76): first defined here
/usr/bin/ld: packet_plugin/rjv3/rjv3_hashes/checkV4.o: in function `computePwd':
checkV4.c:(.text+0x7ae): multiple definition of `computePwd'; packet_plugin/rjv3/rjv3_hashes/checkV4.o:checkV4.c:(.text+0x7ae): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:44：minieap] 错误 1

**Comment by updateing** [comment]
Debian 10 上使用 gcc 8.3.0 在 master 分支上没有复现问题。请贴一下 config.mk，以及环境变量中 CC 和 LD 的值。

**Comment by JIANG3330** [comment]
我发现是我在下面重复添加了😂太蠢了哈哈哈…… 谢谢你
#### Choose/Add your modules here ####
PLUGIN_MODULES := \
	packet_plugin_printer \
	packet_plugin_rjv3

# Linux
PLUGIN_MODULES += if_impl_sockraw
PLUGIN_MODULES += packet_plugin_rjv3
# macOS / BSD
# PLUGIN_MODULES += if_impl_bpf

# Other OS
# PLUGIN_MODULES += if_impl_libpcap

# This implementation is not included in the code.
# If you need it, add it yourselves.
# PLUGIN_MODULES += ifaddrs

ENABLE_DEBUG  := false
ENABLE_ICONV  := false
ENABLE_GBCONV := true
STATIC_BUILD  := false

# If your platform has iconv_* integrated into libc, change to false
# Affects dynamic linking
LIBICONV_STANDALONE := false

CUSTOM_CFLAGS :=
CUSTOM_LDFLAGS :=
CUSTOM_LIBS :=

# Example for cross-compiling
CC := aarch64-openwrt-linux-gcc
# ENABLE_ICONV := true
# CUSTOM_CFLAGS += -I/home/me/libiconv-1.14/include
# CUSTOM_LIBS += /home/me/arm/libiconv.a
# PLUGIN_MODULES += ifaddrs
# STATIC_BUILD := true
