### ISSUE TITLE
非指定客户端问题

### ISSUE THREAD

**Issue by rote66** [updateing/minieap#56]
minieap可以和mentohust那样添加锐捷的三个文件过客户端验证的吗

**Comment by ysc3839** [comment]
发一下你那边 Linux 版锐捷客户端看看？如果和我的一样的话，可以直接使用我的 patch。

**Comment by rote66** [comment]
@ysc3839 我们这边不提供linux客户端，只有win的，所以得放802.1x.exe和Suconfig.dat以及那个dll，mentohust是支持放这三个文件的

**Comment by nature2608** [comment]
@rote66 此项目是模拟Linux客户端登录的

**Comment by ysc3839** [comment]
那先试试[这个](http://net.mku.edu.cn/info/1014/1045.htm)能不能用吧。

**Comment by MySelections** [comment]
> 那先试试[这个](http://net.mku.edu.cn/info/1014/1045.htm)能不能用吧。

你好，这个我可以用，请问你的patch文件在哪个位置

**Comment by ysc3839** [comment]
@MySelections https://github.com/ysc3839/openwrt-minieap/blob/gzhu/patches/006-minieap-gzhu.patch

**Comment by MySelections** [comment]
> @MySelections https://github.com/ysc3839/openwrt-minieap/blob/gzhu/patches/006-minieap-gzhu.patch

这个patch是放到openwrt编译吗，还是说可以单独编译二进制文件吗

**Comment by MySelections** [comment]
> @MySelections https://github.com/ysc3839/openwrt-minieap/blob/gzhu/patches/006-minieap-gzhu.patch

我用你编译好的ipk文件认证成功了，非常感谢
