### ISSUE TITLE
无法找到 echo key 的位置，将不能进行心跳

### ISSUE THREAD

**Issue by LordPenguin666** [updateing/minieap#58]
我遇到了和[https://github.com/updateing/minieap/issues/18](https://github.com/updateing/minieap/issues/18)类似的问题

按照您的方法修改了 packet_plugin_rjv3_prop.c 后仍然出现无法进行心跳的情况

这是minieap的success包

`第一行省略`
`0010   01 7e 03 06 01 7e 00 00 13 11 00 1e b6 ab d0 a3   .~...~..........`
`0020   c7 f8 a3 ac ce f7 d0 a3 c7 f8 a3 ac 53 61 6d 2b   ............Sam+`
`0030   cf b5 cd b3 c9 fd bc b6 a3 a1 00 00 13 11 69 00   ..............i.`
`0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0070   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0080   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`00a0   00 00 00 00 00 00 00 00 00 00 00 13 11 01 00 00   ................`
`00b0   00 13 11 01 01 ff ff 37 77 af 7f b3 91 ad 78 ff   .......7w.....x.`
`00c0   ff 7f cb ff 00 00 13 11 3c 5b c4 fa b5 b1 c7 b0   ........<[......`
`00d0   ca b9 d3 c3 b5 c4 b7 fe ce f1 ce aa d1 a7 c9 fa   ................`
`00e0   57 65 62 b0 fc d4 c2 bc c6 b7 d1 3b 0a bc c6 b7   Web........;....`
`00f0   d1 b2 df c2 d4 ce aa b0 fc d4 c2 bc c6 b7 d1 3b   ...............;`
`0100   0a c4 fa b5 b1 c7 b0 ca b9 d3 c3 b5 c4 bd d3 c8   ................`
`0110   eb bf d8 d6 c6 ce aa 57 65 62 b0 fc d4 c2 bc c6   .......Web......`
`0120   b7 d1 3b 00 00 13 11 56 06 00 00 00 00 00 00 13   ..;....V........`
`0130   11 5a 06 00 00 00 35 00 00 13 11 5b 06 0a 00 07   .Z....5....[....`
`0140   fb 00 00 13 11 5c 0a 6e 9b af e9 84 d4 11 02 00   .....\.n........`
`0150   00 13 11 5d 0a 53 8b cf fb 93 b5 78 17 00 00 13   ...].S.....x....`
`0160   11 5e 0a 00 00 00 00 5f 57 d4 78 00 00 13 11 6e   .^....._W.x....n`
`0170   06 00 00 00 8a 00 00 13 11 79 03 02 00 00 13 11   .........y......`
`0180   80 06 00 00 00 00 00 00 13 11 98 06 00 00 00 00   ................`

认证

> [2020/9/9 2:59:03][I] ========================
[2020/9/9 2:59:03][I] MiniEAP 0.92.1已启动
[2020/9/9 2:59:03][I] 正在查找认证服务器
[2020/9/9 2:59:03][I] We send one! 18 1512
[2020/9/9 2:59:03][E] 无法从 /etc/mtab 获取根分区挂载设备信息，请使用 --fake-serial 选项手动指定硬盘序列号: Inappropriate ioctl for device (25)
[2020/9/9 2:59:03][I] We send one! 521 1512
[2020/9/9 2:59:03][I] We got one! 60 1512
[2020/9/9 2:59:03][I] We got one! 60 1512
[2020/9/9 2:59:03][I] 正在回应用户名请求
[2020/9/9 2:59:03][I] We send one! 36 1512
[2020/9/9 2:59:03][E] 无法从 /etc/mtab 获取根分区挂载设备信息，请使用 --fake-serial 选项手动指定硬盘序列号: Inappropriate ioctl for device (25)
[2020/9/9 2:59:03][I] We send one! 539 1512
[2020/9/9 2:59:04][I] We got one! 68 1512
[2020/9/9 2:59:04][I] We got one! 68 1512
[2020/9/9 2:59:04][I] 正在回应密码请求
[2020/9/9 2:59:04][I] We send one! 53 1512
[2020/9/9 2:59:04][E] 无法从 /etc/mtab 获取根分区挂载设备信息，请使用 --fake-serial 选项手动指定硬盘序列号: Inappropriate ioctl for device (25)
[2020/9/9 2:59:04][I] We send one! 572 1512
[2020/9/9 2:59:04][I] We got one! 400 1512
[2020/9/9 2:59:04][D] 字段格式错误，未发现特征值（偏移量 0x2e）
[2020/9/9 2:59:04][I] 服务器通知：
[2020/9/9 2:59:04][I] 东校区，西校区，Sam+系统升级！
[2020/9/9 2:59:04][E] 无法找到 echo key 的位置，将不能进行心跳
[2020/9/9 2:59:04][I] 认证成功`

请问如何解决这个问题

**Comment by updateing** [comment]
上述 issue 中第一个回复所提到的 patch 是否可以解决问题呢？即 https://github.com/updateing/minieap/issues/18#issuecomment-328111219

**Comment by LordPenguin666** [comment]
> 上述 issue 中第一个回复所提到的 patch 是否可以解决问题呢？即 [#18 (comment)](https://github.com/updateing/minieap/issues/18#issuecomment-328111219)

感谢您的回复

已经尝试过修改 packet_plugin/rjv3/packet_plugin_rjv3_prop.c 仍然是
同样的问题
`-               if (_tmp_prop->header2.type == 0) {`
`-                    /* 0x0 prop's len does not include HEADER2 */`
`-                    _content_len = _tmp_prop->header2.len;`
`-                } else if (_tmp_prop->header2.type == 1) {`
`-                    /* Type 0x1 means there is no length info, we have to search for next 00 00 13 11 */`
`+                if (_tmp_prop->header2.type == 0 || _tmp_prop->header2.type == 1) {`
`+                    /* Type 0x0 and 0x1 means there is no accurate length info,`
`+                     * we have to search for next 00 00 13 11`
`+                     */`

这是修改后返回的success包，看起来有一点点不同

`0000   e0 d5 5e 6c 6a c9 00 1a a9 17 ff ff 88 8e 01 00   ..^lj...........`
`0010   01 7e 03 04 01 7e 00 00 13 11 00 1e b6 ab d0 a3   .~...~..........`
`0020   c7 f8 a3 ac ce f7 d0 a3 c7 f8 a3 ac 53 61 6d 2b   ............Sam+`
`0030   cf b5 cd b3 c9 fd bc b6 a3 a1 00 00 13 11 69 00   ..............i.`
`0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0070   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0080   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................`
`00a0   00 00 00 00 00 00 00 00 00 00 00 13 11 01 01 00   ................`
`00b0   00 13 11 01 01 ff ff 37 77 af 7f ed ca 86 e7 ff   .......7w.......`
`00c0   ff 7f cb ff 00 00 13 11 3c 5b c4 fa b5 b1 c7 b0   ........<[......`
`00d0   ca b9 d3 c3 b5 c4 b7 fe ce f1 ce aa d1 a7 c9 fa   ................`
`00e0   57 65 62 b0 fc d4 c2 bc c6 b7 d1 3b 0a bc c6 b7   Web........;....`
`00f0   d1 b2 df c2 d4 ce aa b0 fc d4 c2 bc c6 b7 d1 3b   ...............;`
`0100   0a c4 fa b5 b1 c7 b0 ca b9 d3 c3 b5 c4 bd d3 c8   ................`
`0110   eb bf d8 d6 c6 ce aa 57 65 62 b0 fc d4 c2 bc c6   .......Web......`
`0120   b7 d1 3b 00 00 13 11 56 06 00 00 00 00 00 00 13   ..;....V........`
`0130   11 5a 06 00 00 00 35 00 00 13 11 5b 06 0a 00 07   .Z....5....[....`
`0140   fb 00 00 13 11 5c 0a 6e 9b af e9 84 d4 11 02 00   .....\.n........`
`0150   00 13 11 5d 0a 53 8b cf fb 93 b5 78 17 00 00 13   ...].S.....x....`
`0160   11 5e 0a 00 00 00 00 5f 58 c8 f3 00 00 13 11 6e   .^....._X......n`
`0170   06 00 00 00 8a 00 00 13 11 79 03 02 00 00 13 11   .........y......`
`0180   80 06 00 00 00 00 00 00 13 11 98 06 00 00 00 00   ................`

**Comment by LordPenguin666** [comment]
这是掉线时的提示，不知道有没有帮助

> [2020/9/9 5:34:29][I] 认证成功
> [2020/9/9` 5:49:29][I] We got one! 60 60
> [2020/9/9 5:49:29][I] 服务器通知：
> [2020/9/9 5:49:29][I] 
> [2020/9/9 5:49:29][E] 认证掉线，正在退出……
> [2020/9/9 5:49:29][W] 无法删除 PID 文件
> [2020/9/9 5:49:29][I] MiniEAP 已退出

**Comment by updateing** [comment]
试一下这个 patch：

```diff
diff --git a/packet_plugin/rjv3/packet_plugin_rjv3_prop.c b/packet_plugin/rjv3/packet_plugin_rjv3_prop.c
index 09f059c..1e5d76f 100644
--- a/packet_plugin/rjv3/packet_plugin_rjv3_prop.c
+++ b/packet_plugin/rjv3/packet_plugin_rjv3_prop.c
@@ -185,7 +185,8 @@ RESULT parse_rjv3_buf_to_prop_list(LIST_ELEMENT** list, uint8_t* buf, int buflen
                 if (_tmp_prop->header2.type == 0) {
                     /* 0x0 prop's len does not include HEADER2 */
                     _content_len = _tmp_prop->header2.len;
-                } else if (_tmp_prop->header2.type == 1) {
+                } else if (_tmp_prop->header2.type == 1
+                            || _tmp_prop->header2.len < sizeof(RJ_PROP_HEADER2) - sizeof(_tmp_prop->header2.magic)) {
                     /* Type 0x1 means there is no length info, we have to search for next 00 00 13 11 */
                     uint8_t* _next_magic = find_byte_pattern(_magic, sizeof(_magic),
                                                               buf + _read_len, buflen - _read_len);
```

这个问题是因为 整包偏移 0x3a 处的那个 prop 的 len 字段为 0，程序以为它真的是 0 字节长，所以计算 _content_len 时下溢，就找不到后面的 prop 了。我这里用上面提供的包测试，已经可以找到 echo key.

**Comment by LordPenguin666** [comment]
> 试一下这个 patch：
> 
> ```diff
> diff --git a/packet_plugin/rjv3/packet_plugin_rjv3_prop.c b/packet_plugin/rjv3/packet_plugin_rjv3_prop.c
> index 09f059c..1e5d76f 100644
> --- a/packet_plugin/rjv3/packet_plugin_rjv3_prop.c
> +++ b/packet_plugin/rjv3/packet_plugin_rjv3_prop.c
> @@ -185,7 +185,8 @@ RESULT parse_rjv3_buf_to_prop_list(LIST_ELEMENT** list, uint8_t* buf, int buflen
>                  if (_tmp_prop->header2.type == 0) {
>                      /* 0x0 prop's len does not include HEADER2 */
>                      _content_len = _tmp_prop->header2.len;
> -                } else if (_tmp_prop->header2.type == 1) {
> +                } else if (_tmp_prop->header2.type == 1
> +                            || _tmp_prop->header2.len < sizeof(RJ_PROP_HEADER2) - sizeof(_tmp_prop->header2.magic)) {
>                      /* Type 0x1 means there is no length info, we have to search for next 00 00 13 11 */
>                      uint8_t* _next_magic = find_byte_pattern(_magic, sizeof(_magic),
>                                                                buf + _read_len, buflen - _read_len);
> ```
> 
> 这个问题是因为 整包偏移 0x3a 处的那个 prop 的 len 字段为 0，程序以为它真的是 0 字节长，所以计算 _content_len 时下溢，就找不到后面的 prop 了。我这里用上面提供的包测试，已经可以找到 echo key.

感谢您的回复，
现在问题已经成功解决，谢谢！
