### ISSUE TITLE
写成 systemd 服务发现的问题

### ISSUE THREAD

**Issue by HuLingOAO** [updateing/minieap#59]
在 minieap.service 文件使用 ExecStop=/usr/local/bin/minieap -k 退出后台服务返回值为 255
看了源码也没发现是哪里返回的。。。
可能是 exit_handler() 关闭 log 文件那个函数哪里？我的启动参数是 -b 1
但在 minieap.c 文件的 exit_handler() 函数最后加上 exit(0); 可以解决那个返回值的问题

应该不会导致啥问题吧。。。

**Comment by Droid-MAX** [comment]
我一般不写ExecStop
