### ISSUE TITLE
字段格式错误，未发现特征值（偏移量 0x6）

### ISSUE THREAD

**Issue by MyCodingSucks** [updateing/minieap#60]
[2020/11/7 20:31:45][I] ========================
[2020/11/7 20:31:45][I] MiniEAP 0.93已启动
[2020/11/7 20:31:45][I] 正在查找认证服务器
[2020/11/7 20:31:45][I] We send one! 18 1512
[2020/11/7 20:31:45][I] We send one! 517 1512
[2020/11/7 20:31:45][I] We got one! 60 60
[2020/11/7 20:31:45][I] We got one! 60 60
[2020/11/7 20:31:45][I] 正在回应用户名请求
[2020/11/7 20:31:45][I] We send one! 34 1512
[2020/11/7 20:31:45][I] We send one! 533 1512
[2020/11/7 20:31:45][I] We got one! 60 60
[2020/11/7 20:31:45][I] We got one! 60 60
[2020/11/7 20:31:45][I] 正在回应密码请求
[2020/11/7 20:31:45][I] We send one! 51 1512
[2020/11/7 20:31:45][I] We send one! 566 1512
[2020/11/7 20:31:45][I] We got one! 68 68
[2020/11/7 20:31:45][I] We got one! 68 68
[2020/11/7 20:31:45][I] 正在回应密码请求
[2020/11/7 20:31:45][I] We send one! 51 1512
[2020/11/7 20:31:45][I] We send one! 566 1512
[2020/11/7 20:31:45][I] We got one! 60 60
[2020/11/7 20:31:45][D] 字段格式错误，未发现特征值（偏移量 0x6）
[2020/11/7 20:31:45][I] We got one! 60 60
[2020/11/7 20:31:45][W] 认证失败 1 次，将在 30 秒或服务器请求后重试……

---

設備是 Redmi AC2100 (openwrt snapshot)
現在一點頭緒都沒有，也不會抓包 (抓了也看不懂
於是來請大佬們幫下忙了，網路上也沒有相關的資料

**Comment by updateing** [comment]
还是抓一下包吧，我可以尝试着分析一下。

**Comment by MyCodingSucks** [comment]
> 还是抓一下包吧，我可以尝试着分析一下。

是用 wireshark 嗎

**Comment by MyCodingSucks** [comment]
> 还是抓一下包吧，我可以尝试着分析一下。

感覺抓得不好 (
不會用 tcpdump ...

[test.zip](https://github.com/updateing/minieap/files/5506031/test.zip)

**Comment by updateing** [comment]
抓包内容看起来挺齐全，但是服务端没有返回任何错误信息，不知道为什么失败了……

用 `--service default` 试一下？

**Comment by Droid-MAX** [comment]
抓包文件当中多处出现以太网帧检查序列不正确，不知道是否有影响

**Comment by MyCodingSucks** [comment]
> 抓包内容看起来挺齐全，但是服务端没有返回任何错误信息，不知道为什么失败了……
> 
> 用 `--service default` 试一下？

**Comment by MyCodingSucks** [comment]
> 抓包内容看起来挺齐全，但是服务端没有返回任何错误信息，不知道为什么失败了……
> 
> 用 `--service default` 试一下？

變成了「使用了非管理員指定的客戶端」

**Comment by MyCodingSucks** [comment]
被 ban 號了
版本號一不小心改成了 4.44
（逃

**Comment by ysc3839** [comment]
如果可以的话，发一下你那里提供的 Linux 客户端？有可能是需要修改一些参数的。

**Comment by MyCodingSucks** [comment]
[RG_Supplicant_For_Linux_V1.31.zip](https://github.com/updateing/minieap/files/5542311/RG_Supplicant_For_Linux_V1.31.zip)

thinking
（還沒被解 ban 的我

**Comment by ysc3839** [comment]
@MyCodingSucks 对比了我校提供的客户端，仅仅是 SuConfig.dat 不一样，可以试试这个[patch](https://github.com/ysc3839/openwrt-minieap/blob/gzhu/patches/006-minieap-gzhu.patch)。

@updateing 顺便问一下，SuConfig.dat 是起什么作用的呢？

**Comment by Droid-MAX** [comment]
我记得某些版本的mentohust有时候也会用到这个文件，具体用途不明

**Comment by MyCodingSucks** [comment]
阿這
我一直以為是什麼設定檔

**Comment by MyCodingSucks** [comment]
@ysc3839 以前好像編譯過這個，跑起來這樣（也可能我編譯了另一個？

root@OpenWrt:~# minieap -u  -p  -n wan -a 1 -d 2 --module rjv3

[I] ========================
[I] MiniEAP 0.92.1已启动
[I] 正在查找认证服务器
[I] 正在回应用户名请求
[I] 正在回应密码请求
[D] 字段格式错误，未发现特征值（偏移量 0x21）
[I] 服务器通知：
[I] 用户不允许使用本服务!
[W] 认证失败 1 次，将在 30 秒或服务器请求后重试……
[I] 正在回应用户名请求
[D] 字段格式错误，未发现特征值（偏移量 0xc）
[W] 认证失败 2 次，将在 30 秒或服务器请求后重试……
[I] 正在回应用户名请求
[I] 正在回应用户名请求
[I] 正在回应密码请求
[D] 字段格式错误，未发现特征值（偏移量 0x21）
[I] 服务器通知：
[I] 用户不允许使用本服务!
[E] 认证失败 3 次，已达到指定次数，正在退出……
[I] MiniEAP 已退出

**Comment by updateing** [comment]
可能还是 `--service default` 的问题。

至于 SuConfig.dat，我没有研究过……

**Comment by ysc3839** [comment]
@MyCodingSucks `用户不允许使用本服务` 应该是服务名称错误。建议用官方的客户端登录一下，好像会显示当前服务名的。

**Comment by MyCodingSucks** [comment]
@ysc3839 沒找到（windows 的

**Comment by nature2608** [comment]
> @ysc3839 沒找到（windows 的

上自助管理能看到服务名的

**Comment by MyCodingSucks** [comment]
服務是 default 沒問題

**Comment by MyCodingSucks** [comment]
> @MyCodingSucks 对比了我校提供的客户端，仅仅是 SuConfig.dat 不一样，可以试试这个[patch](https://github.com/ysc3839/openwrt-minieap/blob/gzhu/patches/006-minieap-gzhu.patch)。
> 
> @updateing 顺便问一下，SuConfig.dat 是起什么作用的呢？

好了，這個 patch 有用
命令改成 minieap -u  -p  -n wan -a 1 -d 2 --module rjv3 --service default 就認證成功了
謝謝大佬們

**Comment by jinchengll** [comment]
@MyCodingSucks 你好，我现在的报错跟你的一样，请问你最后是怎么用这个patch解决的？

**Comment by MyCodingSucks** [comment]
> @MyCodingSucks 你好，我现在的报错跟你的一样，请问你最后是怎么用这个patch解决的？

抱歉最近忙回覆有點遲
就編譯那個 patch 的 minieap，命令再加上 —service default，
但不同學校可能用不同服務吧，看看自己學校的配置改下命令
