### ISSUE TITLE
锐捷 v6.86.2019.07.24 认证无法通过

### ISSUE THREAD

**Issue by Dark-Existed** [updateing/minieap#61]
在 v6.86.2019.07.24上无法通过认证   
学校不提供Linux客户端    
使用命令如下  
```shell
minieap -u username -p password -n eth0.2 --module rjv3 -a 1 -d 1 --fake-serial FWU672GY
```  
![Snipaste_2021-03-11_23-42-21](https://user-images.githubusercontent.com/24956657/110814023-02f8e900-82c4-11eb-80bc-88e4be859616.png)

麻烦您提供一些帮助

**Comment by Dark-Existed** [comment]
![image](https://user-images.githubusercontent.com/24956657/110814578-89adc600-82c4-11eb-999f-a244bcbc5bae.png)

**Comment by ysc3839** [comment]
建议先在网上找个 Linux 的锐捷客户端试试能否认证。

**Comment by nature2608** [comment]
@Dark-Existed 提示用户不允许使用本服务，建议看此issus[https://github.com/updateing/minieap/issues/40](url).先处理服务名问题。

**Comment by jinchengll** [comment]
@Dark-Existed 你好，我学校今年升级，客户端版本跟你一样，我交叉编译后，执行认证报错跟你一样，请问你现在解决了吗？

**Comment by Dark-Existed** [comment]
> @Dark-Existed 你好，我学校今年升级，客户端版本跟你一样，我交叉编译后，执行认证报错跟你一样，请问你现在解决了吗？

白天都在实验室 我晚上回去看看 按 nature2608 他给的建议是说 --service 有问题

**Comment by jinchengll** [comment]
@Dark-Existed 
哈哈，你也是福大的吗？方便加个联系方式？

**Comment by UMRnInside** [comment]
@Dark-Existed @jinchengll 
`service` 字段似乎为 `default`
```
[2021/3/12 21:03:34][I] ========================
[2021/3/12 21:03:34][I] MiniEAP 0.93已启动
[2021/3/12 21:03:34][I] 正在查找认证服务器
[2021/3/12 21:03:34][I] We send one! 18 1512
[2021/3/12 21:03:34][I] We got one! 64 1512
[2021/3/12 21:03:34][I] 正在回应用户名请求
[2021/3/12 21:03:34][I] We send one! 32 1512
[2021/3/12 21:03:34][I] We got one! 64 1512
[2021/3/12 21:03:34][I] 正在回应密码请求
[2021/3/12 21:03:34][I] We send one! 49 1512
[2021/3/12 21:03:35][I] We got one! 64 1512
[2021/3/12 21:03:35][I] 服务器通知：
[2021/3/12 21:03:35][I] 
不允许使用的客户端类型!

```

**Comment by Dark-Existed** [comment]
> @Dark-Existed @jinchengll
> `service` 字段似乎为 `default`
> 
> ```
> [2021/3/12 21:03:34][I] ========================
> [2021/3/12 21:03:34][I] MiniEAP 0.93已启动
> [2021/3/12 21:03:34][I] 正在查找认证服务器
> [2021/3/12 21:03:34][I] We send one! 18 1512
> [2021/3/12 21:03:34][I] We got one! 64 1512
> [2021/3/12 21:03:34][I] 正在回应用户名请求
> [2021/3/12 21:03:34][I] We send one! 32 1512
> [2021/3/12 21:03:34][I] We got one! 64 1512
> [2021/3/12 21:03:34][I] 正在回应密码请求
> [2021/3/12 21:03:34][I] We send one! 49 1512
> [2021/3/12 21:03:35][I] We got one! 64 1512
> [2021/3/12 21:03:35][I] 服务器通知：
> [2021/3/12 21:03:35][I] 
> 不允许使用的客户端类型!
> ```

如果是福大的话 方便留个邮箱或者 什么联系方式吗 我们一起拉个群  
default 这个我们下午找到了

**Comment by UMRnInside** [comment]
@Dark-Existed QQ: 253960216
（稍后删除）

**Comment by feng150416** [comment]
> > @Dark-Existed @jinchengll
> > `service` 字段似乎为 `default`
> > ```
> > [2021/3/12 21:03:34][I] ========================
> > [2021/3/12 21:03:34][I] MiniEAP 0.93已启动
> > [2021/3/12 21:03:34][I] 正在查找认证服务器
> > [2021/3/12 21:03:34][I] We send one! 18 1512
> > [2021/3/12 21:03:34][I] We got one! 64 1512
> > [2021/3/12 21:03:34][I] 正在回应用户名请求
> > [2021/3/12 21:03:34][I] We send one! 32 1512
> > [2021/3/12 21:03:34][I] We got one! 64 1512
> > [2021/3/12 21:03:34][I] 正在回应密码请求
> > [2021/3/12 21:03:34][I] We send one! 49 1512
> > [2021/3/12 21:03:35][I] We got one! 64 1512
> > [2021/3/12 21:03:35][I] 服务器通知：
> > [2021/3/12 21:03:35][I] 
> > 不允许使用的客户端类型!
> > ```
> 
> 如果是福大的话 方便留个邮箱或者 什么联系方式吗 我们一起拉个群
> default 这个我们下午找到了

你建个群吧，然后我们加进去

**Comment by nature2608** [comment]
学校不提供Linux的话使用minieap是无效的（包括模拟linux客户端的mentohust），因为在锐捷sam上取消了linux客户端的认证。可向你校网络中心提出使用linux的需求，有可能就会把你账号权限打开。

**Comment by Dark-Existed** [comment]
> 学校不提供Linux的话使用minieap是无效的（包括模拟linux客户端的mentohust），因为在锐捷sam上取消了linux客户端的认证。可向你校网络中心提出使用linux的需求，有可能就会把你账号权限打开。

感谢 你的建议 我们跟网管要到了Linux客户端 还没来得及试能不能用

**Comment by Dark-Existed** [comment]
> > > @Dark-Existed @jinchengll
> > > `service` 字段似乎为 `default`
> > > ```
> > > [2021/3/12 21:03:34][I] ========================
> > > [2021/3/12 21:03:34][I] MiniEAP 0.93已启动
> > > [2021/3/12 21:03:34][I] 正在查找认证服务器
> > > [2021/3/12 21:03:34][I] We send one! 18 1512
> > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > [2021/3/12 21:03:34][I] 正在回应用户名请求
> > > [2021/3/12 21:03:34][I] We send one! 32 1512
> > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > [2021/3/12 21:03:34][I] 正在回应密码请求
> > > [2021/3/12 21:03:34][I] We send one! 49 1512
> > > [2021/3/12 21:03:35][I] We got one! 64 1512
> > > [2021/3/12 21:03:35][I] 服务器通知：
> > > [2021/3/12 21:03:35][I] 
> > > 不允许使用的客户端类型!
> > > ```
> > 
> > 
> > 如果是福大的话 方便留个邮箱或者 什么联系方式吗 我们一起拉个群
> > default 这个我们下午找到了
> 
> 你建个群吧，然后我们加进去

你好 我们已经建了个群 麻烦联系我的邮箱 de233@qq.com

**Comment by kernelbin** [comment]
> > > @Dark-Existed @jinchengll
> > > `service` 字段似乎为 `default`
> > > ```
> > > [2021/3/12 21:03:34][I] ========================
> > > [2021/3/12 21:03:34][I] MiniEAP 0.93已启动
> > > [2021/3/12 21:03:34][I] 正在查找认证服务器
> > > [2021/3/12 21:03:34][I] We send one! 18 1512
> > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > [2021/3/12 21:03:34][I] 正在回应用户名请求
> > > [2021/3/12 21:03:34][I] We send one! 32 1512
> > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > [2021/3/12 21:03:34][I] 正在回应密码请求
> > > [2021/3/12 21:03:34][I] We send one! 49 1512
> > > [2021/3/12 21:03:35][I] We got one! 64 1512
> > > [2021/3/12 21:03:35][I] 服务器通知：
> > > [2021/3/12 21:03:35][I] 
> > > 不允许使用的客户端类型!
> > > ```
> > 
> > 
> > 如果是福大的话 方便留个邮箱或者 什么联系方式吗 我们一起拉个群
> > default 这个我们下午找到了
> 
> 你建个群吧，然后我们加进去

也是福大的摸到了这里233 所以问题解决了吗&&有群了吗

**Comment by Dark-Existed** [comment]
> > > > @Dark-Existed @jinchengll
> > > > `service` 字段似乎为 `default`
> > > > ```
> > > > [2021/3/12 21:03:34][I] ========================
> > > > [2021/3/12 21:03:34][I] MiniEAP 0.93已启动
> > > > [2021/3/12 21:03:34][I] 正在查找认证服务器
> > > > [2021/3/12 21:03:34][I] We send one! 18 1512
> > > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > > [2021/3/12 21:03:34][I] 正在回应用户名请求
> > > > [2021/3/12 21:03:34][I] We send one! 32 1512
> > > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > > [2021/3/12 21:03:34][I] 正在回应密码请求
> > > > [2021/3/12 21:03:34][I] We send one! 49 1512
> > > > [2021/3/12 21:03:35][I] We got one! 64 1512
> > > > [2021/3/12 21:03:35][I] 服务器通知：
> > > > [2021/3/12 21:03:35][I] 
> > > > 不允许使用的客户端类型!
> > > > ```
> > > 
> > > 
> > > 如果是福大的话 方便留个邮箱或者 什么联系方式吗 我们一起拉个群
> > > default 这个我们下午找到了
> > 
> > 
> > 你建个群吧，然后我们加进去
> 
> 也是福大的摸到了这里233 所以问题解决了吗&&有群了吗

参考[这里](https://github.com/Dark-Existed/MentoHUST-FZU-OpenWrt) readme 里面 的三种提示

**Comment by Dark-Existed** [comment]
> > > > @Dark-Existed @jinchengll
> > > > `service` 字段似乎为 `default`
> > > > ```
> > > > [2021/3/12 21:03:34][I] ========================
> > > > [2021/3/12 21:03:34][I] MiniEAP 0.93已启动
> > > > [2021/3/12 21:03:34][I] 正在查找认证服务器
> > > > [2021/3/12 21:03:34][I] We send one! 18 1512
> > > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > > [2021/3/12 21:03:34][I] 正在回应用户名请求
> > > > [2021/3/12 21:03:34][I] We send one! 32 1512
> > > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > > [2021/3/12 21:03:34][I] 正在回应密码请求
> > > > [2021/3/12 21:03:34][I] We send one! 49 1512
> > > > [2021/3/12 21:03:35][I] We got one! 64 1512
> > > > [2021/3/12 21:03:35][I] 服务器通知：
> > > > [2021/3/12 21:03:35][I] 
> > > > 不允许使用的客户端类型!
> > > > ```
> > > 
> > > 
> > > 如果是福大的话 方便留个邮箱或者 什么联系方式吗 我们一起拉个群
> > > default 这个我们下午找到了
> > 
> > 
> > 你建个群吧，然后我们加进去
> 
> 也是福大的摸到了这里233 所以问题解决了吗&&有群了吗

参考[这里](https://github.com/Dark-Existed/MentoHUST-FZU-OpenWrt) readme 里面 的三种提示

**Comment by kernelbin** [comment]
> > > > > @Dark-Existed @jinchengll
> > > > > `service` 字段似乎为 `default`
> > > > > ```
> > > > > [2021/3/12 21:03:34][I] ========================
> > > > > [2021/3/12 21:03:34][I] MiniEAP 0.93已启动
> > > > > [2021/3/12 21:03:34][I] 正在查找认证服务器
> > > > > [2021/3/12 21:03:34][I] We send one! 18 1512
> > > > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > > > [2021/3/12 21:03:34][I] 正在回应用户名请求
> > > > > [2021/3/12 21:03:34][I] We send one! 32 1512
> > > > > [2021/3/12 21:03:34][I] We got one! 64 1512
> > > > > [2021/3/12 21:03:34][I] 正在回应密码请求
> > > > > [2021/3/12 21:03:34][I] We send one! 49 1512
> > > > > [2021/3/12 21:03:35][I] We got one! 64 1512
> > > > > [2021/3/12 21:03:35][I] 服务器通知：
> > > > > [2021/3/12 21:03:35][I] 
> > > > > 不允许使用的客户端类型!
> > > > > ```
> > > > 
> > > > 
> > > > 如果是福大的话 方便留个邮箱或者 什么联系方式吗 我们一起拉个群
> > > > default 这个我们下午找到了
> > > 
> > > 
> > > 你建个群吧，然后我们加进去
> > 
> > 
> > 也是福大的摸到了这里233 所以问题解决了吗&&有群了吗
> 
> 参考[这里](https://github.com/Dark-Existed/MentoHUST-FZU-OpenWrt) readme 里面 的三种提示

非常感谢！明天试试看

**Comment by AspireKuan** [comment]
您好，我这边测试的时候，出现的问题是：“正在查找认证服务器”，然后提示：“在2状态已经停留了3次，达到指定次数，正在退出”。这种问题是minieap参数没有设置正确吗？
