### ISSUE TITLE
求助：锐捷认证失败（openWRT 5.10内核）

### ISSUE THREAD

**Issue by refined-fish** [updateing/minieap#66]
**环境：操作系统为openWRT 5.10内核，安装了minieap-taiga_0.93.7-beta2-2_x86_64.ipk插件包，配合luci-proto-minieap图形界面使用
**认证方式：学校为锐捷web端认证，连接后浏览器跳转web认证界面输入账号密码登录，无其他认证客户端
**图形界面与命令行均进行过测试，使用命令如下：
   minieap -u username -p password -n eth1 --module printer --module rjv3 --module printer --dhcp-type d(全都试过) --fake-serial 随机序列号
**得到的反馈如下：（图示测试未加序列号）
![image](https://user-images.githubusercontent.com/93998080/154803970-1c9a2d47-b84f-4012-b17a-7cedc9726456.png)
不知道为什么链认证服务器都找不到

**Comment by updateing** [comment]
minieap 是用于锐捷 802.1x 认证的，而非 web 认证。您需要其他的认证方案以解决问题。

**Comment by refined-fish** [comment]
> minieap 是用于锐捷 802.1x 认证的，而非 web 认证。您需要其他的认证方案以解决问题。

感谢您的回复，我们学校曾经使用客户端登录，有可能是更新web认证之后禁用了原认证方式

**Comment by shenyebuwu** [comment]
请问解决了吗

**Comment by refined-fish** [comment]
> 请问解决了吗

如作者所言，我校使用的是网页认证登录，并非老锐捷的802.1x认证，该插件在老锐捷上依旧有效甚至使用旧版锐捷认证插件也是可以的，至于类似我这样的新认证方式则需要对症下药，我这边的网页认证挺好解决的，抓包看看认证post的是什么，然后自己照着样子伪造一份，加一个有无网络的验证，然后每5秒运行一次，有网则等待5s再运行，无网络则自动post认证信息认证（简单来讲相当于雇佣一个机器人每5s查看是否需要登录网页输入账号密码）
