### ISSUE TITLE
认证成功，但网络缓慢？

### ISSUE THREAD

**Issue by Asttear** [updateing/minieap#69]
如题，认证成功后可以正常上网，网速测试也是正常的，但是网页经常出现`DNS_PROBE_FINISHED_NXDOMAIN`或者`DNS_PROBE_FINISHED_BAD_CONFIG`之类的错误，有时甚至完全无法使用网络。已经排除过路由器固件、硬件相关的问题。我想问下这个是否和 OpenWrt 或者认证参数配置有关？

**Comment by updateing** [comment]
minieap 只负责完成 L2 的认证，L3 及更高层影响不到，这个问题与 minieap 应当没有太大关系。

抛开这一点来看，既然网速测试正常，报错又报的是 DNS 问题，那应该首先考虑 DNS 地址设置是否正确、是否符合当前环境。

**Comment by Asttear** [comment]
> 

是的，我也在路由器和本地分别更换 DNS 服务器测试过，还尝试过使用 SmartDNS 等等插件，都没有改善。
使用学校的认证客户端无此问题，并且我发现通过客户端获得的 IP 地址为 `10.50.x.x`，而路由器获得的 IP 地址总是 `10.71.x.x`，不清楚是否有关。
麻烦请问一下，如果要进行下一步排查应该怎样做？是否应该分别抓包对比字段？

**Comment by updateing** [comment]
如果说原版客户端没有问题的话，可以看看 minieap 里面 `--service` 是不是需要特别指定。
