### ISSUE TITLE
使用了非管理员指定的客户端!

### ISSUE THREAD

**Issue by yifancy** [updateing/minieap#73]
========================
Mon Sep  5 17:29:45 2022 daemon.notice netifd: test (6931): [I] MiniEAP 0.92.1已启动
Mon Sep  5 17:29:45 2022 daemon.notice netifd: test (6931): [I] 正在查找认证服务器
Mon Sep  5 17:29:45 2022 daemon.notice netifd: test (6931): [I] 正在回应用户名请求
Mon Sep  5 17:29:45 2022 daemon.notice netifd: test (6931): [I] 正在回应密码请求
Mon Sep  5 17:29:45 2022 daemon.notice netifd: test (6931): [I] 服务器通知：
Mon Sep  5 17:29:45 2022 daemon.notice netifd: test (6931): [I] 使用了非管理员指定的客户端!
Mon Sep  5 17:29:45 2022 daemon.notice netifd: test (6931): [W] 认证失败 1 次，将在 30 秒或服务器请求后重试……
Mon Sep  5 17:29:54 2022 daemon.notice netifd: test (6931): [I] 正在回应用户名请求
Mon Sep  5 17:29:54 2022 daemon.notice netifd: test (6931): [D] 字段格式错误，未发现特征值（偏移量 0xc）
Mon Sep  5 17:29:54 2022 daemon.notice netifd: test (6931): [W] 认证失败 2 次，将在 30 秒或服务器请求后重试……
Mon Sep  5 17:29:57 2022 daemon.notice netifd: test (6931): [I] 正在回应用户名请求
Mon Sep  5 17:29:57 2022 daemon.notice netifd: test (6931): [I] 正在回应密码请求
Mon Sep  5 17:29:57 2022 daemon.notice netifd: test (6931): [I] 服务器通知：
Mon Sep  5 17:29:57 2022 daemon.notice netifd: test (6931): [I] 使用了非管理员指定的客户端!
Mon Sep  5 17:29:57 2022 daemon.notice netifd: test (6931): [E] 认证失败 3 次，已达到指定次数，正在退出……
Mon Sep  5 17:29:57 2022 daemon.notice netifd: test (6931): [I] MiniEAP 已退出
Mon Sep  5 17:29:57 2022 daemon.notice netifd: test (6936): minieap: Program exited with code 1.
Mon Sep  5 17:29:57 2022 daemon.notice netifd: Interface 'test' is now down

**Comment by updateing** [comment]
issue 区有几位其他大学的同学分享了适用于他们学校的修改版本，可试试能否使用。

**Comment by yifancy** [comment]
没有找到，可否分享一个修改特征字段的教程
