### ISSUE TITLE
能认证成功，但无法心跳

### ISSUE THREAD

**Issue by TPOP2000** [updateing/minieap#83]
我的问题与 #18 与 #58 一样，都是认证成功但无法心跳：

> [2024/1/22 0:28:55][D] 字段格式错误，未发现特征值（偏移量 0x6）
[2024/1/22 0:28:55][E] 无法找到 echo key 的位置，将不能进行心跳
[2024/1/22 0:28:55][I] 认证成功

但是我得到的success包很奇怪，是这样的：
```
第一行省略
0010   00 04 03 03 00 04 00 00 00 00 00 00 00 00 00 00   ................
0020   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 00 00 00 00 00 00 00 3d 9f 91 6e   ............=..n
```

**Comment by TPOP2000** [comment]
解决了，原来是我们学校认证方式很特殊

**Comment by Heinrich2818** [comment]
可以提供一下解决方案吗，遇到了同样的问题，谢谢

**Comment by TPOP2000** [comment]
就是minieap原版是通过发送心跳包维持心跳，而我校的是要通过发送认证信息维持心跳。所以要修改eap_state_machine.c状态停留到指定次数时退出的代码，以及运行时要设置-t参数。

**Comment by Heinrich2818** [comment]
十分感谢您的回复！我并没有系统的学习过计算机网络相关的知识，在这方面是纯小白，所以以下内容请您指正：为了minieap可用，需要修改比较短的单个认证超时时间（-t参数），在eap_state_machine添加超时对应的重新发送认证信息的代码，这样每次超时之后就会调用这部分代码实现不断认证。


以上理解不知道是不是您所说的实现方式，如果是的话，这种反复认证的方式是否有可能会被ban机呢，您在使用中是否遇到过什么其他问题？此外如果方便的话，是否可以提供您的eap_state_machine.c文件供我参考修改？


不知道您是不是sysu的同校校友，十分感谢您的帮助和热心回复！

---Original---
From: ***@***.***&gt;
Sent at: 2024年9月1日(Sun) PM2:48
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [updateing/minieap] 能认证成功，但无法心跳 (Issue #83)




 
就是minieap原版是通过发送心跳包维持心跳，而我校的是要通过发送认证信息维持心跳。所以要修改eap_state_machine.c状态停留到指定次数时退出的代码，以及运行时要设置-t参数。

**Comment by TPOP2000** [comment]
我将修改后的minieap源码发给你
[https://res.public.onecdn.static.microsoft/assets/mail/file-icon/png/zip_16x16.png]minieap.zip<https://1drv.ms/u/c/982ecdbc9cd15bea/EfOkqYUBHFpMu3fiZqKwfEMBYSAdv4Hoxsl4OwJ5CODiIw>
________________________________
发件人: Heinrich2818 ***@***.***>
发送时间: 2024年9月1日 15:18
收件人: updateing/minieap ***@***.***>
抄送: TPOP2000 ***@***.***>; State change ***@***.***>
主题: Re: [updateing/minieap] 能认证成功，但无法心跳 (Issue #83)


十分感谢您的回复！我并没有系统的学习过计算机网络相关的知识，在这方面是纯小白，所以以下内容请您指正：为了minieap可用，需要修改比较短的单个认证超时时间（-t参数），在eap_state_machine添加超时对应的重新发送认证信息的代码，这样每次超时之后就会调用这部分代码实现不断认证。


以上理解不知道是不是您所说的实现方式，如果是的话，这种反复认证的方式是否有可能会被ban机呢，您在使用中是否遇到过什么其他问题？此外如果方便的话，是否可以提供您的eap_state_machine.c文件供我参考修改？


不知道您是不是sysu的同校校友，十分感谢您的帮助和热心回复！

---Original---
From: ***@***.***&gt;
Sent at: 2024年9月1日(Sun) PM2:48
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [updateing/minieap] 能认证成功，但无法心跳 (Issue #83)





就是minieap原版是通过发送心跳包维持心跳，而我校的是要通过发送认证信息维持心跳。所以要修改eap_state_machine.c状态停留到指定次数时退出的代码，以及运行时要设置-t参数。

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

―

**Comment by TPOP2000** [comment]
我是通过抓包发现其认证方式的，修改后的minieap与官方认证程序往来数据是基本一致的，所以不会被ban，我使用半年多也没有被ban。-t参数我是设置为30。
________________________________
发件人: Heinrich2818 ***@***.***>
发送时间: 2024年9月1日 15:18
收件人: updateing/minieap ***@***.***>
抄送: TPOP2000 ***@***.***>; State change ***@***.***>
主题: Re: [updateing/minieap] 能认证成功，但无法心跳 (Issue #83)


十分感谢您的回复！我并没有系统的学习过计算机网络相关的知识，在这方面是纯小白，所以以下内容请您指正：为了minieap可用，需要修改比较短的单个认证超时时间（-t参数），在eap_state_machine添加超时对应的重新发送认证信息的代码，这样每次超时之后就会调用这部分代码实现不断认证。


以上理解不知道是不是您所说的实现方式，如果是的话，这种反复认证的方式是否有可能会被ban机呢，您在使用中是否遇到过什么其他问题？此外如果方便的话，是否可以提供您的eap_state_machine.c文件供我参考修改？


不知道您是不是sysu的同校校友，十分感谢您的帮助和热心回复！

---Original---
From: ***@***.***&gt;
Sent at: 2024年9月1日(Sun) PM2:48
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [updateing/minieap] 能认证成功，但无法心跳 (Issue #83)





就是minieap原版是通过发送心跳包维持心跳，而我校的是要通过发送认证信息维持心跳。所以要修改eap_state_machine.c状态停留到指定次数时退出的代码，以及运行时要设置-t参数。

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

―

**Comment by Lookinfres** [comment]
但是这么做的话 中间会间歇性认证失败然后没网 坐标东校区😫
