### ISSUE TITLE
无法结束minieap 进程

### ISSUE THREAD

**Issue by cj6pku** [updateing/minieap#85]
使用minieap认证成功后连接网络，使用minieap -k退出认证后仍然能够访问网络

**Comment by updateing** [comment]
1. 进程是否结束可以通过 ps 得到验证，通过网络访问状态推断进程状态是不合逻辑的。
2. minieap 所做的事情是“通知”上级交换机身份、使其为当前设备开放数据通道，并不能掌握数据通道的主动开关权。这一权利始终在交换机上。杀死 minieap 后，网络的通断完全取决于交换机上的认证条目会不会超时、何时超时，与 minieap 没有关系。
