### ISSUE TITLE
交叉编译到openwrt平台时是否必须添加libiconv和getifaddrs支持

### ISSUE THREAD

**Issue by Droid-MAX** [updateing/minieap#9]
我给minieap编译成ipk了，但如果开启libiconv支持，在编译时会报一些头文件找不到的错误，交叉编译得到libiconv库后又报有三个不支持的libiconv函数，我想只要不静态编译的话libiconv是不是可以不选？

**Comment by updateing** [comment]
1. 如果你是要在编译连同 libiconv 一起编译的话，那很抱歉， Openwrt / LEDE 自带的 libiconv 根本不能用。看编译出来的文件大小就知道了。包括 libiconv-full 并开启完整语言支持也没用。
2. 如果你是独立于编译环境下载的 libiconv 1.14 的话，要参考 config.mk 里面的交叉编译示例，同时把工具链里面的 iconv.h 删掉。如果想要动态链接，去掉 LIBS，LDFLAGS 加上 `-liconv -L/path/to/libiconv` 即可。

libiconv 跟是不是静态链接没有关系。能带的话还是尽量带上吧，万一出错可以看到是什么错误原因。

---

getifaddrs 必须要，读 IP 和 MAC 地址要用到。这又是旧版本 OP 的一个坑，明明不占多大体积却非要除外。建议用 LEDE，musl 里面有这函数，不用另外准备。

**Comment by Droid-MAX** [comment]
getifaddrs就不大清楚如何添加了。。。

**Comment by Droid-MAX** [comment]
https://github.com/Droid-MAX/minieap
我这里把minieap编译成ipk的东西都准备好了，只不过默认没有添加libiconv和getifaddrs支持。。

**Comment by Droid-MAX** [comment]
另外，关于minieap的luci应用可以套用mentohust的luci来进行二次开发我想是可行的

**Comment by lyq1996** [comment]
我来这里报道一下..
交叉编译如果带上 libiconv，编译出来的大小2072KB..不带的话773KB。
另外还有一个不明白..
好像后台模式有点问题，输出关不掉，会一直输出到终端(求确认！)。

**Comment by lyq1996** [comment]
@updateing

**Comment by updateing** [comment]
你是用的哪一种后台？我用的 `-b3` 没有问题，相关代码在[这里](https://github.com/updateing/minieap/blob/master/config.c#L26)

此外我带了 libiconv，整个程序全部静态链接，也只有 1.3M 而已，strip 以后有 1.1M 左右（ARM 架构）。
x86 动态链接 170KB 左右。不太清楚为什么那么大…… 你是带了 libpcap 吗？

**Comment by lyq1996** [comment]
我用的是sock raw，架构是mipsel，关于后台可能是我出现幻觉了..
我先用`-b2`然后`-w`了，再去查看配置文件发现是`-b3` ....
两次都是这样，然后就没搞了，看来应该是我操作有问题。

**Comment by updateing** [comment]
[手动 doge 脸](https://github.com/updateing/minieap/blob/master/config.c#L274)

（讲真不明白为什么会有后台但输出到控制台这个选项，在什么情况下会用得到……）

**Comment by lyq1996** [comment]
我知道原因了…
用[`-h`](https://github.com/updateing/minieap/blob/master/config.c#L108)输出帮助信息说`-b 2`是关闭输出…
然而[代码里](https://github.com/updateing/minieap/blob/master/config.c#L36)却是 `-b 1`关闭输出…

**Comment by updateing** [comment]
https://github.com/updateing/minieap/commit/b25c846e6eac3b7a5f621e901f49bd1beef6661e :-|

**Comment by marcong95** [comment]
@updateing 不知可否指导下怎么找到ifaddrs的实现呢，百度google都翻了好久，都似乎找不到相关信息，是要去Linux内核源码里面找吗？？

此外，make的时候提示如下
```
util//misc.o: In function `gbk2utf8':
misc.c:(.text+0x634): undefined reference to `iconv_open'
misc.c:(.text+0x660): undefined reference to `iconv'
misc.c:(.text+0x66c): undefined reference to `iconv_close'
collect2: ld returned 1 exit status
```
而且，我`nm libiconv.a`的时候只能找到叫做libiconv_xx的符号，并没有iconv，不知道是不是我的iconv编译出了什么问题？

**Comment by updateing** [comment]
1. 先检查你的 C 库里有没有这个函数。如果不选择 ifaddrs 模块就过不了编译，再去寻找。一般可以去你所用的 C 库的完整源码找。

2. 在 `CUSTOM_CFLAGS` 加 `-I` 指定正确的 libiconv 下的 include 路径。必要的话可以试试删除工具链里的 iconv.h.

**Comment by ch-wu** [comment]
我用 make menuconfig 设置编译openwrt ipk，识别不出minieap相关选项，请问Makefile的写法格式是不是不对？
和这个 Makefile（这个项目可以顺利编译） 对比：
[https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk/blob/master/Makefile](url)

**Comment by ysc3839** [comment]
@ch-wu 建议参考 https://github.com/ysc3839/openwrt-minieap/blob/master/Makefile

**Comment by ch-wu** [comment]
> @ch-wu 建议参考 https://github.com/ysc3839/openwrt-minieap/blob/master/Makefile
谢谢😀
